wip: secure xenon communication
checking integration tests with auth enabled,
sleep if not able to monitore
fixing java tests, adjust start/stop
more to deployment curl, add more logging on failure

Change-Id: I9d9a94629db3e463c407c6207116c4ec8a59bf31

diff --git a/devbox-photon/Vagrantfile b/devbox-photon/Vagrantfile
--- a/devbox-photon/Vagrantfile
+++ b/devbox-photon/Vagrantfile
@@ -21,6 +21,8 @@ Vagrant.configure("2") do |config|
 
   DOCKER_PORT=ENV["DOCKER_PORT"] || 2375
   PROTOCOL = ENV['ENABLE_AUTH'] == 'true' ? "https" : "http"
+  DEPLOYMENT_SEED_CURL_OPTS = ENV['ENABLE_AUTH'] == 'true' ? "--cert /etc/keys/machine.crt \
+  --key /etc/keys/machine.privkey --cacert /etc/keys/cacert.crt" : ""
 
   # Output directory for scripts generated by vagrantfile
   SCRIPT_DIR="/home/vagrant/bin"
@@ -485,6 +487,7 @@ end
         private_network_lw_ip = ENV["PRIVATE_NETWORK_LW_IP"] || "172.31.253.67"
         dynamic_params += %Q(,\n  "LIGHTWAVE_HOSTNAME" : "#{private_network_lw_ip}")
       end
+
     else
       dynamic_params += %Q(,\n  "ENABLE_AUTH" : false)
       dynamic_params += %Q(,\n  "APIFE_PORT" : "28080")
@@ -719,6 +722,37 @@ EOM
     $out
   EOS
 
+  deployment_create_spec_json = %Q(
+    { "state" : "READY",
+      "imageDataStoreNames" : ["#{ENV['ESX_DATASTORE']}"],
+      "imageDataStoreUsedForVMs" : "true",
+      "imageId" : "none",
+      "projectId" : "none",
+      "virtualNetworkEnabled" : "false",
+      "documentSelfLink" : "test-deployment")
+   if ENV['ENABLE_AUTH'] == 'true'
+     deployment_create_spec_json += %Q(,\n
+        "oAuthEnabled" : true,
+        "oAuthTenantName" : "#{ENV['LW_DOMAIN_NAME']}",
+        "oAuthSecurityGroups" : "[#{ENV['LW_DOMAIN_NAME']}\\Administrators]",
+        "oAuthUserName" : "ec-admin@#{ENV['LW_DOMAIN_NAME']}",
+        "oAuthPassword" : "#{ENV['LW_PASSWORD']}",
+        "oAuthServerAddress" : "#{ENV['PUBLIC_LW_NETWORK_IP']}",
+        "oAuthServerPort" : 443)
+   else
+    deployment_create_spec_json += %Q(,\n
+       "oAuthEnabled" : false)
+   end
+   if ENV['STATS_ENABLED']
+      deployment_create_spec_json += %Q(,\n
+       "statsStorePort" : "#{ENV['STATS_STORE_PORT']}",
+       "statsStoreEndpoint" : "#{ENV['STATS_STORE_ENDPOINT']}")
+   end
+   deployment_create_spec_json += %Q(,\n
+     "statsEnabled" : "#{ENV['STATS_ENABLED']}")
+
+   deployment_create_spec_json += "\n}"
+
   #
   # Generate service check script, gets called by start-all script
   #
@@ -747,14 +781,37 @@ cat > $out <<-'EOM'
   i=0
   while (($i < $MAX_RETRIES))
   do
-    status=$(curl -s --connect-timeout 60 --max-time 60 --header "Authorization: Bearer #{API_SHARED_SECRET}" #{PROTOCOL}://127.0.0.1:9000/status/)
-    if [ "READY" == "$(echo $status | jq -r '.status')" ]; then
-      echo "Services started successfully"
-      exit 0
+    # Check that our service is ready by checking the available api is reachable
+    status=$(curl -w "%{http_code}" -o /tmp/out.txt -k -sS --connect-timeout 60 --max-time 60 \
+    --header "Authorization: Bearer #{API_SHARED_SECRET}" #{PROTOCOL}://127.0.0.1:9000/available)
+
+    if [[ $status == 2* ]]; then
+       echo "Services started successfully"
+
+       # Send a post to create a deployment entity to CloudStore, DEPLOYMENT_SEED_CURL_OPTS are needed for
+       # an auth enabled deployment containing the private key, certificate, and cacert.
+       # This is sent directly because for an auth enabled deployment, a token is needed for API access which
+       # is checked against the auth endpoint in the deployment entity.
+
+       echo "Seeding deployment state"
+       status=$(docker exec photon-controller-core curl -sS -w "%{http_code}" #{DEPLOYMENT_SEED_CURL_OPTS} \
+       -H "Content-type: application/json" -d "#{deployment_create_spec_json}" -o /tmp/out.txt \
+       #{PROTOCOL}://#{network_ip}:19000/photon/cloudstore/deployments)
+
+       if [[ $status != 2* ]]; then
+         echo "Seeding deployment failed"
+         echo #{deployment_create_spec_json}
+         cat /tmp/out.txt
+         exit 1
+       fi
+       echo "Seeding deployment successful"
+
+     exit 0
+
     fi
     # Print current statuses
     echo "Service status:"
-    echo $status | jq -r '.components[] | .component + ": " + .status'
+    echo $status
     echo "Retry count: $i"
     sleep $SLEEP_BETWEEN_RETRIES_SEC
     ((i++))
@@ -766,7 +823,7 @@ chmod +x $out
 end
 
 
-#
+  #
   # Clean log directory if selected
   #
   if ENV["DEVBOX_CLEAN_LOGS"]
