devbox: adjusted Vagrant file to work with PhotonOS v1.0
- had to change some permissions to make installed binaries accessible
  PhotonOS is not setting global permissions through chmod unless they
  are explicitly set
- stopped building the lightwave container it is now part of the box
  image
- ensured that zookeeper is started in standalone mode
- fixed small issues
- added proper wait for docker
- removed fake agent left overs
- created photon-controller-core container build target that doesn't force
  a servicebase container rebuild

Change-Id: I03a82c63323117ded5059766410859fa07f8b4d2

diff --git a/devbox-photon/Vagrantfile b/devbox-photon/Vagrantfile
--- a/devbox-photon/Vagrantfile
+++ b/devbox-photon/Vagrantfile
@@ -50,11 +50,6 @@ Vagrant.configure("2") do |config|
   #
   config.vm.provider "virtualbox"
 
-  restart_always = "--restart=always"
-  if ENV["NO_RESTART_ALWAYS"]
-    restart_always = ""
-  end
-
   # Where to save dynamic parameters
   dynamic_params_file = "/home/vagrant/dynamic-params.json"
 
@@ -107,12 +102,14 @@ Vagrant.configure("2") do |config|
     end
   end
 
-  # Install jsonlint, useful for catching errors in dynamic_params early
-  config.vm.provision :shell, :inline  => <<-EOM
-    tdnf makecache
-    tdnf install -y gmp-devel
-    gem install jsonlint --no-rdoc --no-ri
-  EOM
+  config.vm.provision :shell, :privileged => false, :inline => <<-EOS
+    set -xe
+    sudo systemctl start docker.service
+    sudo chmod a+x /usr/bin/mustache
+    sudo chmod a+x /usr/bin/jsonlint
+    sudo chmod -R a+rx /usr/bin
+    sudo chmod -R a+rx /usr/lib/ruby
+  EOS
 
   #
   # VM definition for lightwave
@@ -154,7 +151,7 @@ Vagrant.configure("2") do |config|
     end
 
     # Configure network
-    if ENV["PUBLIC_NETWORK_IP"]
+    if ENV["PUBLIC_LW_NETWORK_IP"]
       public_network_ip = ENV["PUBLIC_LW_NETWORK_IP"]
       network_ip = public_network_ip
       bridge_network = ENV["BRIDGE_NETWORK"]
@@ -169,7 +166,6 @@ Vagrant.configure("2") do |config|
         ip route del default
         ip route add default via #{public_network_gateway} dev enp0s8
       EOS
-      ENV["DOCKER_URL"] = ENV["DOCKER_URL"] || "http://#{public_network_ip}:#{DOCKER_PORT}"
     else
       private_network_lw_ip = ENV["PRIVATE_NETWORK_LW_IP"] || "172.31.253.67"
       lightwave.vm.network :private_network, ip: private_network_lw_ip
@@ -181,11 +177,10 @@ Vagrant.configure("2") do |config|
     lightwave.vm.hostname = "lightwave"
 
     lightwave.vm.provision :shell, :privileged => false, :inline => <<-EOS
-      set -xe
-      sleep 15 # docker takes longer to come up in RC1
-      docker tag devbox/compileservices photon/compileservices
+cat > #{dynamic_params_file} <<'EOM'
+{}
+EOM
     EOS
-
     #
     # Generate Lightwave container start script
     #
@@ -195,9 +190,6 @@ Vagrant.configure("2") do |config|
 out="#{SCRIPT_DIR}/start-lightwave"
 cat > $out <<-'EOM'
   #!/bin/bash
-
-  docker build -t vmware/lightwave-sts /devbox_data/java/containers/lightwave
-
   config_build_dir="/devbox_data/java/containers/lightwave/build/config"
   mkdir -p $config_build_dir
   combined_params=$(jq -s '.[0] * (.[1]#{CONFIG_JQ_FILTER})' #{dynamic_params_file} #{lightwave_config_file})
@@ -279,13 +271,6 @@ $out
       photon.vm.network :forwarded_port, guest: 2375, host: DOCKER_PORT
     end
 
-    photon.vm.provision :shell, :privileged => false, :inline => <<-EOS
-      set -xe
-      sleep 15 # docker takes longer to come up in RC1
-      docker tag devbox/compileservices photon/compileservices
-    EOS
-
-
     # ================ NETWORK CONFIGURATION ================
 
     #
@@ -317,7 +302,6 @@ $out
     # Configure hostname
     #
     photon.vm.hostname = "devbox"
-
 
     dynamic_params = %Q(
     {
@@ -411,30 +395,24 @@ $out
     dynamic_params += "\n}"
 
     # Write dynamic_params file
-    config.vm.provision :shell, :privileged => false, :inline => <<-EOS
+    photon.vm.provision :shell, :privileged => false, :inline => <<-EOS
 cat > #{dynamic_params_file} <<'EOM'
   #{dynamic_params}
 EOM
-  EOS
+    EOS
 
-  # Validate dynamic_params file, catch errors early
-  config.vm.provision :shell, :inline => <<-EOS
-    printf "Validating dynamic params JSON file:"
-    jsonlint #{dynamic_params_file}
-    if [[ $? != 0 ]]; then
-      echo "Validation failed for file:"
-      cat #{dynamic_params_file}
-      exit 1
-    fi
-  EOS
+    # Validate dynamic_params file, catch errors early
+    photon.vm.provision :shell, :inline => <<-EOS
+      printf "Validating dynamic params JSON file:"
+      jsonlint #{dynamic_params_file}
+      if [[ $? != 0 ]]; then
+        echo "Validation failed for file:"
+        cat #{dynamic_params_file}
+        exit 1
+      fi
+    EOS
 
   # ================ PROVISIONING ================
-
-  # renaming esxcloud containers to zookeeper Containers
-  photon.vm.provision :shell, :inline => <<-EOS
-    docker tag devbox/zookeeper photon/zookeeper
-    docker tag devbox/haproxy photon/haproxy
-  EOS
 
   #
   # Give access to zookeeper user inside container to write to log directory in host
@@ -458,6 +436,7 @@ cat > $out <<-'EOM'
 # This avoids vagrant shared folder issues with hard links.
 # Only copy files needed for agent build, exclude all else.
 sudo mkdir -p /mirror/devbox_data
+sudo chown -R vagrant /mirror
 time sudo rsync -rLgotp --exclude="develop" /devbox_data/python /mirror/devbox_data
 time sudo rsync -rLgotp /devbox_data/thrift /mirror/devbox_data
 
@@ -469,7 +448,7 @@ container=$(docker run -d \
   -e "GIT_REVISION=#{GIT_REVISION}" \
   photon/compileservices /var/compileservices/agent_compile_install.sh)
 docker attach $container
-docker commit $container devbox/agent
+#docker commit $container devbox/agent
 
 # Copy for use by integration test
 sudo mkdir -p /var/esxcloud/packages
@@ -478,95 +457,6 @@ sudo cp /mirror/devbox_data/python/dist/*.vib /var/esxcloud/packages/
 if #{ENV["ENVOY_VIB_URL"]}
   sudo wget #{ENV["ENVOY_VIB_URL"]} -P /var/esxcloud/packages/
 end
-EOM
-chmod +x $out
-  EOS
-
-  agent_parameters_file = "/home/vagrant/agent-parameters.json"
-  # Make sure agent params file exists so that mustache doesn't fail
-  photon.vm.provision :shell, :privileged => false, :inline => "touch #{agent_parameters_file}"
-
-  if !(ENV["PUBLIC_NETWORK_IP"] || ENV["REAL_AGENT"])
-    agent_parameters = %Q(
-    {
-      "AGENT_BIND_ADDRESS": "#{network_ip}",
-      "AGENT_LOG_PATH": "/var/log",
-      "AGENT_ZOOKEEPER": "#{network_ip}:2181")
-    if(ENV['ESX_AGENT_COUNT'])
-     agent_parameters += %Q(,\n  "AGENT_COUNT": "#{ENV['ESX_AGENT_COUNT']}")
-    end
-    agent_parameters += "\n}"
-
-    # Validate agent parameters JSON
-    config.vm.provision :shell, :privileged => false, :inline => <<-EOS
-cat > #{agent_parameters_file} <<-'EOM'
-#{agent_parameters}
-EOM
-    EOS
-
-    config.vm.provision :shell, :privileged => false, :inline => <<-EOS
-    printf "Validating dynamic params JSON file:"
-    jsonlint #{agent_parameters_file}
-    if [[ $? != 0 ]]; then
-      echo "Validation failed for file:"
-      cat #{agent_parameters_file}
-      exit 1
-    fi
-    EOS
-  end
-
-  #
-  # Start agent script
-  #
-  photon.vm.provision :shell, :privileged => false, :inline => <<-EOS
-set -ex
-out=#{SCRIPT_DIR}/start-agent
-cat > $out <<-'EOM'
-#!/bin/bash -xe
-
-agent_config_dir=/devbox_data/java/devbox/agent/configuration
-
-mkdir -p #{agent_config_build_dir}
-for file in $agent_config_dir/*.#{CONFIG_EXTS}
-do
-  if [ -f $file ]; then
-    output="#{agent_config_build_dir}/$(basename $file)"
-    mustache "#{agent_parameters_file}" $file > "$output"
-    if [[ "${file#*.}" == "sh" ]]; then
-      chmod +x "$output"
-    fi
-  fi
-done
-
-mkdir -p /vagrant/log/agent
-
-# Stop any old running agent container
-docker stop devbox/agent &> /dev/null || true
-docker rm -f devbox/agent &> /dev/null || true
-
-# Start fake agent
-docker run -d -p 8835:8835 \
-  --net=host #{restart_always} \
-  --name=agent \
-  -v /vagrant/log/agent:/var/log \
-  -v /devbox_data/tmp:/devbox_data/tmp \
-  -v #{DATASTORE_DIR}:/tmp \
-  -v #{ESXCLOUD_DIR}:#{ESXCLOUD_DIR} \
-  -v #{agent_config_build_dir}:/etc/esxcloud/agent \
-  devbox/agent /etc/esxcloud/agent/run.sh
-EOM
-chmod +x $out
-  EOS
-
-  #
-  # Stop agent script
-  #
-  photon.vm.provision :shell, :privileged => false, :inline => <<-EOS
-set -ex
-out=#{SCRIPT_DIR}/stop-agent
-cat > $out <<-'EOM'
-#!/bin/bash -x
-docker stop agent
 EOM
 chmod +x $out
   EOS
