fix: increase Lightwave server setup attempts
Increase the number of attempts to reach the Lightwave server
as occasionally it is able to connect after almost max
number of attempts currently set.
If the server is still unreachable, it will exit without
continuing building other vms as the error will go unnoticed
and cause issues when running authentication related tests.
Vagrant is also updated so that the lightwave vm is created
only when auth is enabled since it requires correct configuration
and takes resources when trying to use an auth disabled environment.

Change-Id: I7b6de9940f74a706fa2fd71ba13f536b55b5bad1

diff --git a/devbox-photon/Vagrantfile b/devbox-photon/Vagrantfile
--- a/devbox-photon/Vagrantfile
+++ b/devbox-photon/Vagrantfile
@@ -114,6 +114,7 @@ Vagrant.configure("2") do |config|
     gem install jsonlint --no-rdoc --no-ri
   EOM
 
+  if ENV['ENABLE_AUTH'] == 'true'
   #
   # VM definition for lightwave
   #
@@ -189,33 +190,33 @@ Vagrant.configure("2") do |config|
     dynamic_params = %Q(
     {)
 
-    if ENV['ENABLE_AUTH'] == 'true'
-      if ENV['LW_DOMAIN_NAME']
-        dynamic_params += %Q(\n  "LIGHTWAVE_DOMAIN" : "#{ENV['LW_DOMAIN_NAME']}")
-      else
-        abort("auth is enabled for devbox lightwave, but domain is not set")
-      end
 
-      if ENV['LW_PASSWORD']
-        dynamic_params += %Q(,\n  "LIGHTWAVE_PASSWORD" : "#{ENV['LW_PASSWORD']}")
-      else
-        abort("auth is enabled for devbox lightwave, but password is not set")
-      end
-
-      if ENV["PUBLIC_NETWORK_IP"]
-        if ENV["PUBLIC_LW_NETWORK_IP"]
-          # The hostname is set to the IP since Photon Controller does not have DNS set
-          # to Lightwave yet, but Photon Controller during auth enabled needs to
-          # verify the hostname matches the Lightwave server certificate.
-          dynamic_params += %Q(,\n  "LIGHTWAVE_HOSTNAME" : "#{ENV['PUBLIC_LW_NETWORK_IP']}")
-        else
-          abort("auth is enabled for devbox lightwave, but hostname is not set")
-        end
-      else
-        private_network_lw_ip = ENV["PRIVATE_NETWORK_LW_IP"] || "172.31.253.67"
-        dynamic_params += %Q(,\n  "LIGHTWAVE_HOSTNAME" : "#{private_network_lw_ip}")
-      end
+    if ENV['LW_DOMAIN_NAME']
+      dynamic_params += %Q(\n  "LIGHTWAVE_DOMAIN" : "#{ENV['LW_DOMAIN_NAME']}")
+    else
+      abort("auth is enabled for devbox lightwave, but domain is not set")
     end
+
+    if ENV['LW_PASSWORD']
+      dynamic_params += %Q(,\n  "LIGHTWAVE_PASSWORD" : "#{ENV['LW_PASSWORD']}")
+    else
+      abort("auth is enabled for devbox lightwave, but password is not set")
+    end
+
+    if ENV["PUBLIC_NETWORK_IP"]
+      if ENV["PUBLIC_LW_NETWORK_IP"]
+        # The hostname is set to the IP since Photon Controller does not have DNS set
+        # to Lightwave yet, but Photon Controller during auth enabled needs to
+        # verify the hostname matches the Lightwave server certificate.
+        dynamic_params += %Q(,\n  "LIGHTWAVE_HOSTNAME" : "#{ENV['PUBLIC_LW_NETWORK_IP']}")
+      else
+        abort("auth is enabled for devbox lightwave, but hostname is not set")
+      end
+    else
+      private_network_lw_ip = ENV["PRIVATE_NETWORK_LW_IP"] || "172.31.253.67"
+      dynamic_params += %Q(,\n  "LIGHTWAVE_HOSTNAME" : "#{private_network_lw_ip}")
+    end
+
     dynamic_params += "\n}"
 
     # Write dynamic_params file
@@ -313,11 +314,12 @@ cat >> $out <<-'EOM'
   echo "Checking to connect to Lightwave REST client to start"
   attempts=1
   reachable="false"
-  while [ $attempts -lt 30 ] && [ $reachable != "true" ]; do
+  total_attempts=50
+  while [ $attempts -lt $total_attempts ] && [ $reachable != "true" ]; do
     http_code=$(curl -w "%{http_code}" -s -X GET --insecure https://lightwave.#{ENV['LW_DOMAIN_NAME']})
     # The curl returns 000 when it fails to connect to the lightwave server
     if [ $http_code -eq 000 ]; then
-      echo "Lightwave REST server not reachable (attempt $attempts/30), will try again."
+      echo "Lightwave REST server not reachable (attempt $attempts/$total_attempts), will try again."
       attempts=$[$attempts+1]
       sleep 5
     else
@@ -329,15 +331,16 @@ cat >> $out <<-'EOM'
       break
     fi
   done
-  if [ $attempts -eq 30 ]; then
-    echo "Could not connect to Lightwave REST client after 30 attempts, users not added and token expiration not updated."
+  if [ $attempts -eq $total_attempts ]; then
+    echo "Could not connect to Lightwave REST client after $total_attempts attempts, users not added and token expiration not updated."
+    exit 1
   fi
 EOM
 chmod +x $out
 $out
     EOS
   end
-
+  end
 
   #
   # VM definition for photon
