removed unnecessary cert generation checks in install agent script
Change-Id: Ic817b2304c50aea26ba589121806823459fce6b2

diff --git a/java/deployer/src/main/resources/scripts/esx-install-agent2 b/java/deployer/src/main/resources/scripts/esx-install-agent2
--- a/java/deployer/src/main/resources/scripts/esx-install-agent2
+++ b/java/deployer/src/main/resources/scripts/esx-install-agent2
@@ -94,8 +94,6 @@ esxi_host_pem_path="${host_cert_dir}/${pem_name}"
 
 function create_certificate() {
 
-  cert_alias=`keytool --list --keystore /keystore.jks -storepass ${lightwave_password} -alias MACHINE_CERT_${host_address}`
-  if [[ "$cert_alias" == *"does not exist"* ]]; then
     rm -rf ${cert_dir}
     mkdir -p ${cert_dir}
 
@@ -107,33 +105,39 @@ function create_certificate() {
     sed -i s/IPAddress.*/"IPAddress = ${host_address}"/ "${config_file_path}"
 
     # Generate keys if they don't exist
-    if [ ! -f "${priv_key_path}" ] || [ ! -f "${pub_key_path}" ]; then
-      echo "Creating keys for ${host_address}"
-      certool --genkey --privkey="${priv_key_path}" --pubkey="${pub_key_path}" \
-        --srp-upn administrator@${lightwave_domain} --srp-pwd ${lightwave_password} --server ${lightwave_address}
+    echo "Creating keys for ${host_address}"
+    certool --genkey \
+            --privkey="${priv_key_path}" \
+            --pubkey="${pub_key_path}" \
+            --srp-upn administrator@${lightwave_domain} \
+            --srp-pwd ${lightwave_password} \
+            --server ${lightwave_address}
+    rc=$?
+
+    if [ $rc -ne 0 ]; then
+        echo "Failed to create key. Error: $rc"
+        return $rc
     fi
 
     # Generate certificate if it doesn't exist
-    if [ ! -f "${host_crt_path}" ]; then
-      echo "Creating cert for ${host_address}"
-      certool --gencert --privkey="${priv_key_path}" --cert="${host_crt_path}" \
-        --srp-upn administrator@${lightwave_domain} --srp-pwd ${lightwave_password} \
-        --server ${lightwave_address} --config "${config_file_path}"
+    echo "Creating cert for ${host_address}"
+    certool --gencert \
+            --privkey="${priv_key_path}" \
+            --cert="${host_crt_path}" \
+            --srp-upn administrator@${lightwave_domain} \
+            --srp-pwd ${lightwave_password} \
+            --server ${lightwave_address} \
+            --config "${config_file_path}"
+    rc=$?
 
-      cat ${host_crt_path} ${priv_key_path} > ${host_pem_path}
-
-      # Generate pkcs12 keystore
-      openssl pkcs12 -export -in ${host_crt_path} -inkey ${priv_key_path} -out hostkeystore.p12 -name MACHINE_CERT_${host_address} \
-        -password pass:${lightwave_password}
-
-      # Convert it into JKS
-      keytool -importkeystore -deststorepass ${lightwave_password} -destkeypass ${lightwave_password} \
-        -destkeystore /keystore.jks -srckeystore hostkeystore.p12 -srcstoretype PKCS12 -srcstorepass ${lightwave_password} \
-        -alias MACHINE_CERT_${host_address}
+    if [ $rc -ne 0 ]; then
+        echo "Failed to create certificate. Error: $rc"
+        return $rc
     fi
-  else
-    echo "create_certificate skipped because cert_alias already exists"
-  fi
+
+    cat ${host_crt_path} ${priv_key_path} > ${host_pem_path}
+
+    return 0
 }
 
 function create_certificate_no_auth() {
@@ -173,6 +177,11 @@ then
   if [ "$create_cert" == "true" ]
   then
     create_certificate
+    rc=$?
+    if [ $rc -ne 0 ]; then
+        echo "Failed to generate certificate for ESXi host"
+        exit $rc
+    fi
   else
     # this is the cert generated by default through
     create_certificate_no_auth
