deployer/upgrade: retry failed provisioning tasks
- to ensure we only provision hosts that were actually running we now exclude any host that is not provisioned or in error state
- if either an install or remove we retry once

Change-Id: Ibf1f3fa12dc376941f6c45688b13107c3b344955

diff --git a/java/deployer/src/main/resources/scripts/esx-install-agent2 b/java/deployer/src/main/resources/scripts/esx-install-agent2
--- a/java/deployer/src/main/resources/scripts/esx-install-agent2
+++ b/java/deployer/src/main/resources/scripts/esx-install-agent2
@@ -51,18 +51,36 @@ esxcli -s $host_address -u $username -p "$password" system syslog reload
 
 fi
 
+function remove_vib() {
+  result=`esxcli -s $host_address -u $username -p "$password" software vib remove -f -n $1 || echo "failed"`
+  if [[ $result == "failed" ]]
+  then
+    echo "retrying remove vib"
+	  esxcli -s $host_address -u $username -p "$password" software vib remove -f -n $1
+	fi
+}
+
+function install_vib() {
+  result=`esxcli -s $host_address -u $username -p "$password" software vib install -f -v $vib_path || echo "failed"`
+  if [[ $result == "failed" ]]
+  then
+    echo "retrying installing vib"
+	  esxcli -s $host_address -u $username -p "$password" software vib install -f -v $vib_path
+	fi
+}
+
 # Remove original agent if existed
 agent_existing=`esxcli -s $host_address -u $username -p "$password" software vib list | grep esxcloud | wc -l`
 if [ $agent_existing -ne 0 ]
 then
-  esxcli -s $host_address -u $username -p "$password" software vib remove -f -n esxcloud
+  remove_vib esxcloud
 fi
 
 # Remove agent if existed
 agent_existing=`esxcli -s $host_address -u $username -p "$password" software vib list | grep photon-controller-agent | wc -l`
 if [ $agent_existing -ne 0 ]
 then
-  esxcli -s $host_address -u $username -p "$password" software vib remove -f -n photon-controller-agent
+  remove_vib photon-controller-agent
 fi
 
-esxcli -s $host_address -u $username -p "$password" software vib install -f -v $vib_path
+install_vib
